### ISSUE TITLE
app.js error

### ISSUE THREAD

**Issue by ghost** [DunnCreativeSS/ForkdeltaEtherdeltaArb#1]
Hello

I want to run app.js
command: node app.js but have error.

Error: Cannot find module 'web3'
    at Function.Module._resolveFilename (module.js:547:15
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\ethereum-js\ap
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Can you help me please? I can't fix it!!

**Comment by ghost** [comment]
I can installed web3 but now have error from web3-eth


> scrypt@6.0.3 preinstall C:\xampp\htdocs\arbitrage\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install C:\xampp\htdocs\arbitrage\node_modules\scrypt
> node-gyp rebuild


C:\xampp\htdocs\arbitrage\node_modules\scrypt>if not defined npm_config_node_gyp
 (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:
\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" re
build )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\arbitrage\node_modules\scrypt
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\xampp\htdocs\arbitra
ge\package.json'
npm WARN arbitrage No description
npm WARN arbitrage No repository field.
npm WARN arbitrage No README data
npm WARN arbitrage No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-05-30T01_58_26_7
31Z-debug.log

**Comment by staccDOTsol** [comment]
Hey fromtr sorry for missing your issue! This repo was basically created so I could easily move project changes from my local machine to Google Cloud Platform. How did you find this repo? Glad to see you're interested :)

There are a ton of npm modules required for starting app.js. Some of them aren't even required for this node project, and some of them (like web3-eth) won't run (easily) on Windows.

For google-spreadsheet you'll need a sheets.google.com spreadsheet, and replace:

var doc = new GoogleSpreadsheet('1SE_ztgj0NnuZ_zvxL-t7kE1Zy-bdjJx4VPQFvgJz01k');

This 1SE_ztgj0NnuZ_zvxL-t7kE1Zy-bdjJx4VPQFvgJz01k with your spreadsheet key, where the one coded in there now is:

https://docs.google.com/spreadsheets/d/1SE_ztgj0NnuZ_zvxL-t7kE1Zy-bdjJx4VPQFvgJz01k/edit#gid=0

and you'll need a header row with these headers:

erc20 | ask | bid | arb | threshold | askVol | bidVol | link 1 | link 2

For this line:

var creds = require('./TwitterPush-5e2367822949.json');

You'll need to obtain your own keys from Google as a json file.

You can find directions on how to get one here:

https://www.npmjs.com/package/google-spreadsheet

Under 'Service Account (recommended method)'

I've removed some of the extra node package requirements, you can now run:

npm install request google-spreadsheet system-sleep socket.io-client mathjs

and put the latest app.js and it should run.

node app.js

here's a screenshot of me using it in Windows:

https://www.screencast.com/t/GmCWNT8elw

donations welcome :) 0xddFA7E953270A6d5A62b6bBF4a2442c4CB41F464 

I haven't been able to test any of the arbs I find because of a lack of funds, there's a chance that Fd/Ed have old orders still showing that error out when you try to act on them. The trick is to be the first in...

https://www.screencast.com/t/taoeOXRkbUx

This is what the final product looks like, it's finding arbs sometimes 40%+!
